import { PrebuildPrompts } from "@/interfaces/prebuildPrompt";

const prebuildPrompts: PrebuildPrompts[] = [
    {
        category: "Prompts for Legal Consumers",
        prompts: [
            'Provide examples of [legal case/issue]',
            'What are my rights as an employee?',
            'How do I file for divorce and what are the requirements?'
        ]
    },
    {
        category: 'Prompts for Legal Research',
        prompts: [
            'How do I create a will or trust?',
            'What are the latest developments in [legal area]?',
            'What are the relevant laws or regulations regarding [legal issue]?',
            'What is the history of [legal case/issue]?',
            'What is the legal definition of [legal term or phrase]',
            'What is the legal precedent for [legal case/issue]?',
            'What are the pros and cons of [legal argument/position]?',
            'What is the standard for [legal issue] in [jurisdiction]?',
            'What are the key legal arguments in [legal case/issue]?',
            'Provide a summary of [case name]',
            'Summarize the following contract: [copy and paste contract]',
            'What is the statute of limitations for [type of case] in [state or jurisdiction]?',
            'Outline the steps involved in [legal process or procedure]',
            'What is the significance of [case name]?',
            'Describe the elements of [legal claim or cause of action]',
            'What are the main defenses to [legal claim or cause of action]?',
            'What is the burden of proof in [type of case]?',
            'Analyze the impact of [legal case/issue] on [specific industry or area of law]',
            'What are the potential consequences or penalties for [legal violation]?',
            'Provide an overview of the [legal issue] in international law',
            'Compare and contrast [legal concept] in different jurisdictions',
            'Compare and contrast the legal concept of negligence in the United States and the United Kingdom.',
            'Discuss the role of [legal principle or concept] in [specific area of law]',
            'Identify the key cases and legal authorities on [legal issue]',
            'Explain the concept of [legal term] and its relevance to [specific area of law]',
            'What are the ethical considerations in [legal issue or situation]?',
            'Describe the role of [legal professional or organization] in [legal system or process]',
            'Discuss the implications of recent legal reforms on [specific area of law]',
            'What are the upcoming changes in [legal area]?',
            'Analyze the potential impact of [legal issue] on [specific group or community]',
            'How have recent court decisions affected the interpretation of [legal principle or concept]?',
            'Discuss the relationship between [legal issue] and [public policy or social issue]',
            'What are the potential implications of [legal case/issue] on future cases or legislation?',
            'What are the key factors that courts consider when interpreting [legal provision or statute]?',
            'How has [legal case/issue] affected [specific industry or sector]?',
            'What is the role of [government agency] in enforcing [legal regulation or requirement]?',
            'Explain the differences between [type of law] and [another type of law]',
            'Discuss the evolution of [legal principle or concept] over time',
            'Describe the various forms of [legal entity or structure].',
            'What are the primary sources of law for [legal issue or area of law]?',
            'Explain the role of [legal document] in [legal process or transaction]',
            'Discuss the importance of [legal principle or concept] in ensuring justice or fairness',
            'Analyze the relationship between [legal issue] and [constitutional provision or principle]',
            'What are the potential remedies for [legal harm or violation]?',
            'Provide examples of [legal case/issue]',
            'What is the legal basis for [government action or regulation]?',
            'Discuss the challenges and limitations of [legal approach or solution] to [problem or issue]',
            'How does [legal case/issue] relate to [similar or related legal case/issue]?',
            'Provide examples of landmark cases in [specific area of law]',
            'How does [legal concept] apply in [real-life situation or hypothetical scenario]?',
            'What are the requirements for [legal action or procedure]?',
            'Analyze the effectiveness of [legal policy or regulation] in addressing [specific issue or problem]',
            'Discuss the role of [legal principle or concept] in promoting [public interest or policy goal]',
            'Explain the rationale behind [legal rule or doctrine]',
            'What are the key factors courts consider in determining [legal issue or outcome]?',
            'Discuss the influence of [legal case/issue] on shaping [public opinion or legal debate]',
            'How has [legal case/issue] been received or criticized by legal scholars and professionals?',
            'Describe the role of [legal institution or body] in [legal system or process]',
            'Explain the hierarchy of courts in [jurisdiction]',
            'What are the main elements of [legal theory or approach]?',
            'Discuss the impact of [legal case/issue] on the interpretation of [constitutional provision or principle]',
            'What are the main challenges and controversies surrounding [legal issue]?',
            'How does the law address [emerging issue or technology]?',
            'Analyze the role of [legal principle] in balancing competing interests or rights',
            'What are the key legal considerations in [business transaction or relationship]?',
            'Explain the importance of [legal issue] in protecting [fundamental right or value]'
        ]
    }
]

export default prebuildPrompts;