import { PrebuildPrompts } from "@/interfaces/prebuildPrompt";

const prebuildPrompts: PrebuildPrompts[] = [
    {
        category: "Prompts for Legal Consumers",
        prompts: [
            'Provide examples of [legal case/issue]',
            'What are my rights as an employee?',
            'How do I file for divorce and what are the requirements?'
        ]
    },
    {
        category: 'Prompts for Legal Research',
        prompts: [
            'How do I create a will or trust?',
            'What are the latest developments in [legal area]?',
            'What are the relevant laws or regulations regarding [legal issue]?',
            'What is the history of [legal case/issue]?',
            'What is the legal definition of [legal term or phrase]',
            'What is the legal precedent for [legal case/issue]?',
            'What are the pros and cons of [legal argument/position]?',
            'What is the standard for [legal issue] in [jurisdiction]?',
            'What are the key legal arguments in [legal case/issue]?',
            'Provide a summary of [case name]',
            'Summarize the following contract: [copy and paste contract]',
            'What is the statute of limitations for [type of case] in [state or jurisdiction]?',
            'Outline the steps involved in [legal process or procedure]',
            'What is the significance of [case name]?',
            'Describe the elements of [legal claim or cause of action]',
            'What are the main defenses to [legal claim or cause of action]?',
            'What is the burden of proof in [type of case]?',
            'Analyze the impact of [legal case/issue] on [specific industry or area of law]',
            'What are the potential consequences or penalties for [legal violation]?',
            'Provide an overview of the [legal issue] in international law',
            'Compare and contrast [legal concept] in different jurisdictions',
            'Compare and contrast the legal concept of negligence in the United States and the United Kingdom.',
            'Discuss the role of [legal principle or concept] in [specific area of law]',
            'Identify the key cases and legal authorities on [legal issue]',
            'Explain the concept of [legal term] and its relevance to [specific area of law]',
            'What are the ethical considerations in [legal issue or situation]?',
            'Describe the role of [legal professional or organization] in [legal system or process]',
            'Discuss the implications of recent legal reforms on [specific area of law]',
            'What are the upcoming changes in [legal area]?',
            'Analyze the potential impact of [legal issue] on [specific group or community]',
            'How have recent court decisions affected the interpretation of [legal principle or concept]?',
            'Discuss the relationship between [legal issue] and [public policy or social issue]',
            'What are the potential implications of [legal case/issue] on future cases or legislation?',
            'What are the key factors that courts consider when interpreting [legal provision or statute]?',
            'How has [legal case/issue] affected [specific industry or sector]?',
            'What is the role of [government agency] in enforcing [legal regulation or requirement]?',
            'Explain the differences between [type of law] and [another type of law]',
            'Discuss the evolution of [legal principle or concept] over time',
            'Describe the various forms of [legal entity or structure].',
            'What are the primary sources of law for [legal issue or area of law]?',
            'Explain the role of [legal document] in [legal process or transaction]',
            'Discuss the importance of [legal principle or concept] in ensuring justice or fairness',
            'Analyze the relationship between [legal issue] and [constitutional provision or principle]',
            'What are the potential remedies for [legal harm or violation]?',
            'Provide examples of [legal case/issue]',
            'What is the legal basis for [government action or regulation]?',
            'Discuss the challenges and limitations of [legal approach or solution] to [problem or issue]',
            'How does [legal case/issue] relate to [similar or related legal case/issue]?',
            'Provide examples of landmark cases in [specific area of law]',
            'How does [legal concept] apply in [real-life situation or hypothetical scenario]?',
            'What are the requirements for [legal action or procedure]?',
            'Analyze the effectiveness of [legal policy or regulation] in addressing [specific issue or problem]',
            'Discuss the role of [legal principle or concept] in promoting [public interest or policy goal]',
            'Explain the rationale behind [legal rule or doctrine]',
            'What are the key factors courts consider in determining [legal issue or outcome]?',
            'Discuss the influence of [legal case/issue] on shaping [public opinion or legal debate]',
            'How has [legal case/issue] been received or criticized by legal scholars and professionals?',
            'Describe the role of [legal institution or body] in [legal system or process]',
            'Explain the hierarchy of courts in [jurisdiction]',
            'What are the main elements of [legal theory or approach]?',
            'Discuss the impact of [legal case/issue] on the interpretation of [constitutional provision or principle]',
            'What are the main challenges and controversies surrounding [legal issue]?',
            'How does the law address [emerging issue or technology]?',
            'Analyze the role of [legal principle] in balancing competing interests or rights',
            'What are the key legal considerations in [business transaction or relationship]?',
            'Explain the importance of [legal issue] in protecting [fundamental right or value]'
        ]
    },
    {
        category: 'Prompts for Drafting Legal Documents',
        prompts: [
            'Draft a Sales Agreement for transferring ownership of a vehicle',
            'Draft a Non-Disclosure Agreement for a startup and an investor',
            'Write a Cease and Desist Letter for copyright infringement',
            'Write a Last Will and Testament for John Doe',
            'What should be included in a Partnership Agreement?',
            'What are the standard clauses for a Lease Agreement?',
            'What are the necessary elements for an Employment Contract?',
            'What are the typical terms for a Prenuptial Agreement?',
            'What are the recommended provisions for a Licensing Agreement?',
            'Provide a template for a Power of Attorney',
            'What are the most common mistakes to avoid when drafting a Commercial Lease Agreement?',
            'Draft a Shareholders Agreement for a newly formed corporation',
            'Write a Separation Agreement for a divorcing couple',
            'Draft a Promissory Note for a loan between friends',
            'Write a Privacy Policy for an e-commerce website',
            'What should be included in a Freelance Services Agreement?',
            'What are the standard clauses for an Independent Contractor Agreement?',
            'What are the necessary elements for a Non-Compete Agreement?',
            'What are the typical terms for a Joint Venture Agreement?',
            'What are the recommended provisions for a Personal Loan Agreement?',
            'Provide a template for a General Release of Liability',
            'What are the most common mistakes to avoid when drafting a Settlement Agreement?',
            'Draft a Guardianship Agreement for a minor child',
            'Write a Deed of Trust for a real estate transaction',
            'Draft a Warranty Deed for the sale of a property',
            'Write a Buy-Sell Agreement for a business partnership',
            'What should be included in a Limited Liability Company (LLC) Operating Agreement?',
            'What are the standard clauses for a Share Purchase Agreement?',
            'What are the necessary elements for an Intellectual Property (IP) Assignment Agreement?',
            'What are the typical terms for a Franchise Agreement?',
            'What are the recommended provisions for a Distribution Agreement?',
            'Provide a template for a Letter of Intent (LOI) for a business acquisition',
            'What are the most common mistakes to avoid when drafting a Service Level Agreement (SLA)?',
            'Draft a Stock Option Plan for a tech startup',
            'Write a Consent to Assignment of Lease for a commercial tenant',
            'Draft a Construction Contract for a residential project',
            'Write a Hold Harmless Agreement for a contractor',
            'What are the standard clauses for a Software Development Agreement?',
            'What are the necessary elements for a Commercial Sublease Agreement?',
            'What are the typical terms for a Co-Founder Agreement?',
            'What are the recommended provisions for a Consulting Agreement?',
            'Provide a template for a Demand Letter for a breach of contract',
            'What are the most common mistakes to avoid when drafting a Merger Agreement?',
            'Draft a Real Estate Purchase Agreement for a residential property',
            'Write a Sponsorship Agreement for a charity event',
            'Draft a Memorandum of Understanding (MOU) for a collaboration between two organizations',
            'Write a Confidentiality Agreement for a product inventor',
            'What should be included in a Proxy Agreement for a shareholder meeting?',
            'What are the standard clauses for a Manufacturing Agreement?',
            'What are the necessary elements for a Supply Agreement?',
            'What are the typical terms for a Website Terms of Service?',
            'What are the recommended provisions for a Waiver of Liability?',
            'Provide a template for an Affidavit of Identity',
            'What are the most common mistakes to avoid when drafting a Rental Agreement?',
            'What should be included in a Security Agreement for a secured loan?',
        ]
    },
    {
        category: 'Prompts for Family Lawyers',
        prompts: [
            "Draft a prenuptial agreement for engaged couples who want to protect their assets",
            "Create a child custody agreement for divorcing parents",
            "Write a postnuptial agreement for spouses who want to modify their marital property rights",
            "Prepare a parenting plan for separated parents to outline their co-parenting responsibilities",
            "Draft a property settlement agreement for a divorcing couple to divide their assets and debts",
            "Write a spousal support agreement for a couple considering divorce",
            "Create a visitation schedule for non-custodial parents to maintain a relationship with their children",
            "Prepare an adoption agreement for a family looking to adopt a child",
            "Draft a guardianship agreement for grandparents who want to become the legal guardians of their grandchildren",
            "Write a paternity petition for a father seeking to establish his legal rights to a child",
            "What should be included in a marital settlement agreement?",
            "What are the standard clauses for a child support agreement?",
            "What are the necessary elements for a decree of dissolution of marriage?",
            "What are the typical terms for a mediated divorce agreement?",
            "What are the recommended provisions for a cohabitation agreement?",
            "Provide a template for a parenting time modification",
            "What are the most common mistakes to avoid when drafting a separation agreement?",
            "Draft a domestic partnership agreement for unmarried couples who want to establish their legal rights",
            "Write a power of attorney for family members to make decisions on behalf of an incapacitated relative",
            "Create a will for a client who wants to ensure their family is provided for after their death",
            "Prepare a living trust for a client who wants to protect their assets and avoid probate",
            "Draft a grandparent visitation petition for grandparents seeking court-ordered visitation with their grandchildren",
            "Write a step-parent adoption petition for a step-parent who wants to adopt their spouse's child",
            "Create a surrogacy agreement for intended parents and their surrogate",
            "Prepare an estate plan for a client looking to protect their family's financial future",
            "Draft a letter of intent for a family member who wants to ensure their wishes are carried out in case of their incapacity",
            "What should be included in a durable power of attorney for healthcare decisions?",
            "What are the standard clauses for a conservatorship agreement?",
            "What are the necessary elements for a family limited partnership?",
            "What are the typical terms for a qualified domestic relations order (QDRO)?",
            "What are the recommended provisions for an intestate succession plan?",
            "Provide a template for a declaration of paternity",
            "What are the most common mistakes to avoid when drafting a post-adoption contact agreement?",
            "Draft a pre-adoption home study for prospective adoptive parents",
            "Write a name change petition for a client who wants to change their legal name",
            "Create a marital property agreement for a couple who want to define their separate and shared assets",
            "Prepare a temporary custody order for a client who needs to establish temporary guardianship of a child",
            "Draft an affidavit of support for a family member seeking to sponsor a relative for immigration purposes",
            "Write a restraining order petition for a client seeking protection from domestic violence",
            "Create a dependency and neglect petition for a client who wants to report child abuse or neglect to the court",
            "What should be included in a family care plan for military families?",
            "What are the standard clauses for a relinquishment of parental rights document?",
            "What are the necessary elements for a termination of parental rights petition?",
            "What are the typical terms for a special needs trust?",
            "What are the recommended provisions for a mediation agreement in a family law dispute?",
            "Provide a template for a stipulation and order to modify child support",
            "What are the most common mistakes to avoid when drafting a collaborative divorce agreement?",
            "Draft a no-contest clause for a client who wants to discourage challenges to their will",
            "Write an emancipation petition for a minor seeking legal independence from their parents",
            "Create a temporary restraining order for a client who needs immediate protection from harassment or abuse",
            "Prepare a qualified terminable interest property (QTIP) trust for a client who wants to provide for their spouse and children from a previous marriage",
            "Draft a conservatorship nomination for a client who wants to appoint a trusted person to manage their affairs in case of incapacity",
            "Write a petition for the appointment of a guardian ad litem for a child involved in a family law dispute",
            "Create an affidavit of voluntary relinquishment of parental rights for a parent who wants to give up their legal rights to a child",
            "Prepare an affidavit of non-paternity for a man who wants to disprove paternity of a child",
            "What should be included in a standby guardianship designation?",
            "What are the standard clauses for a child relocation agreement?",
            "What are the necessary elements for a legal separation agreement?",
            "What are the typical terms for a family law arbitration agreement?",
            "What are the recommended provisions for a declaration of disclosure in a family law case?",
            "Provide a template for an order to show cause in a child custody dispute",
            "What are the most common mistakes to avoid when drafting a family law settlement agreement?",
        ]
    },
    {
        category: 'Prompts for Personal Injury Lawyers',
        prompts: [
            "Draft a demand letter for a slip and fall case",
            "Draft a settlement agreement for a car accident case involving multiple parties",
            "Write a complaint for a medical malpractice lawsuit",
            "Write a motion for summary judgment in a defective product case for client John Doe",
            "What should be included in a negligence claim for a personal injury case?",
            "What are the standard clauses for a personal injury settlement agreement?",
            "What are the necessary elements for a wrongful death claim?",
            "What are the typical terms for a contingent fee agreement in a personal injury case?",
            "What are the recommended provisions for a mediation agreement in a personal injury dispute?",
            "Provide a template for a personal injury interrogatory",
            "What are the most common mistakes to avoid when drafting a personal injury demand letter?",
            "Draft a response to a defendant's motion to dismiss in a premises liability case",
            "Write a deposition outline for a car accident case involving a commercial truck",
            "Draft a retainer agreement for a client with a traumatic brain injury from a workplace accident",
            "Write a motion to compel discovery in a personal injury case against a large corporation",
            "What should be included in a release of all claims for a personal injury settlement?",
            "What are the standard clauses for an arbitration agreement in a personal injury case?",
            "What are the necessary elements for proving liability in a dog bite case?",
            "What are the typical terms for a structured settlement in a personal injury case?",
            "What are the recommended provisions for a confidentiality agreement in a personal injury settlement?",
            "Provide a template for a personal injury witness statement",
            "What are the most common mistakes to avoid when drafting a personal injury complaint?",
            "Draft a counterclaim for a personal injury case involving comparative negligence",
            "Write a request for production of documents in a bicycle accident case",
            "Draft a pre-litigation demand letter for a client injured in a public transportation accident",
            "Write a motion for class certification in a mass tort personal injury case",
            "What should be included in a request for admission in a personal injury case?",
            "What are the standard clauses for a joint venture agreement in a personal injury case involving multiple law firms?",
            "What are the necessary elements for establishing causation in a toxic exposure case?",
            "What are the typical terms for a third-party liability claim in a personal injury case?",
            "What are the recommended provisions for a choice of law clause in a personal injury contract?",
            "Provide a template for a personal injury expert witness report",
            "What are the most common mistakes to avoid when drafting a motion for summary judgment in a personal injury case?",
            "Draft a reply to a defendant's answer in a personal injury case involving a defective medical device",
            "Write a notice of appeal for a denied workers' compensation claim",
            "Draft an opposition to a motion for summary judgment in a personal injury case involving a construction accident",
            "Write a motion for sanctions in a personal injury case involving spoliation of evidence",
            "What should be included in a protective order for a personal injury case?",
            "What are the standard clauses for a co-counsel agreement in a multi-district personal injury litigation?",
            "What are the necessary elements for proving gross negligence in a personal injury case?",
            "What are the typical terms for a subrogation agreement in a personal injury case?",
            "What are the recommended provisions for a forum selection clause in a personal injury contract?",
            "Provide a template for a personal injury case management plan",
            "What are the most common mistakes to avoid when drafting a personal injury appeal brief?",
            "Draft a petition for approval of a minor's personal injury settlement",
            "Write a request for interrogatories in a pedestrian accident case",
            "Draft a response to a defendant's counterclaim in a personal injury case involving assault and battery",
            "Write a motion to exclude expert testimony in a personal injury case involving a questionable expert witness",
            "What should be included in a personal injury litigation hold letter?",
            "What are the standard clauses for a fee-sharing agreement in a personal injury case involving multiple attorneys?",
            "What are the necessary elements for proving vicarious liability in a personal injury case?",
            "What are the typical terms for a lien resolution agreement in a personal injury case?",
            "What are the recommended provisions for a severance agreement in a personal injury case involving multiple defendants?",
            "Provide a template for a personal injury jury selection questionnaire",
            "What are the most common mistakes to avoid when drafting a personal injury mediation brief?",
            "Draft a response to a request for production of documents in a personal injury case involving a defective product",
            "Write a motion in limine to exclude prejudicial evidence in a personal injury trial",
            "Draft an opposition to a motion to dismiss in a personal injury case involving a governmental entity",
            "Write a letter of representation to an insurance company for a client injured in a motor vehicle accident",
            "What should be included in a personal injury case status update letter to a client?",
            "What are the standard clauses for a referral agreement in a personal injury case involving an out-of-state attorney?",
            "What are the necessary elements for proving intentional infliction of emotional distress in a personal injury case?",
            "What are the typical terms for a personal injury attorney's contingency fee agreement?",
            "What are the recommended provisions for a settlement negotiation strategy in a personal injury case?",
            "Provide a template for a personal injury trial exhibit list",
            "What are the most common mistakes to avoid when drafting a personal injury closing argument?",
        ]
    },
    {
        category: 'Prompts for Employment and Labor lawyers',
        prompts: [
            "Draft a non-disclosure agreement for a new employee.",
            "Draft a termination letter for an employee dismissal.",
            "Write a workplace harassment policy for a small business.",
            "Write a collective bargaining agreement for a labor union and a company.",
            "What should be included in a severance agreement?",
            "What are the standard clauses for an employment contract?",
            "What are the necessary elements for a workplace safety policy?",
            "What are the typical terms for an independent contractor agreement?",
            "What are the recommended provisions for a non-compete agreement?",
            "Provide a template for a workplace accommodation request letter.",
            "What are the most common mistakes to avoid when drafting a whistleblower policy?",
            "Draft a family and medical leave policy for a company.",
            "Write a wage and hour compliance policy for an organization.",
            "Create a social media policy for employees of a corporation.",
            "What should be included in an employee handbook for a startup?",
            "What are the standard clauses for a workers' compensation policy?",
            "Draft a confidentiality agreement for a company merger.",
            "Write a settlement agreement for an employment discrimination case.",
            "What are the necessary elements for a reasonable accommodation policy under the ADA?",
            "What are the typical terms for an executive employment agreement?",
            "What are the recommended provisions for a workplace drug and alcohol policy?",
            "Provide a template for a request for reasonable accommodation under the ADA.",
            "What are the most common mistakes to avoid when drafting a workplace diversity and inclusion policy?",
            "Draft a workplace violence prevention policy for a retail business.",
            "Write a telecommuting policy for a remote work environment.",
            "Create a disciplinary action policy for a company.",
            "What should be included in a sexual harassment prevention training program?",
            "What are the standard clauses for an arbitration agreement in an employment context?",
            "Draft a performance improvement plan for an underperforming employee.",
            "Write a grievance procedure for a labor union.",
            "What are the necessary elements for an effective anti-discrimination policy?",
            "What are the typical terms for a temporary employment agreement?",
            "What are the recommended provisions for an employee stock option plan?",
            "Provide a template for an employee warning notice.",
            "What are the most common mistakes to avoid when drafting a workplace health and wellness program?",
            "Draft an equal employment opportunity policy for a medium-sized business.",
            "Write a vacation and paid time off policy for a company.",
            "Create a conflict of interest policy for a non-profit organization.",
            "What should be included in a code of conduct for a professional association?",
            "What are the standard clauses for a trade secret protection agreement?",
            "Draft a layoff notice for a company restructuring.",
            "Write a retaliation prevention policy for an organization.",
            "What are the necessary elements for a progressive discipline policy?",
            "What are the typical terms for a severance pay agreement?",
            "What are the recommended provisions for a workplace dress code policy?",
            "Provide a template for an employee performance evaluation.",
            "What are the most common mistakes to avoid when drafting a wage garnishment policy?",
            "Draft a workplace privacy policy for a technology company.",
            "Write a pension plan policy for a large corporation.",
            "Create an overtime policy for a manufacturing business.",
            "What should be included in a workplace investigation procedure?",
            "What are the standard clauses for an employee intellectual property agreement?",
            "Draft a reasonable accommodation request denial letter for an employer.",
            "Write a workplace safety training program for a construction company.",
            "What are the necessary elements for a workplace lactation policy?",
            "What are the typical terms for a flexible work arrangement policy?",
            "What are the recommended provisions for a workplace ethics policy?",
            "Provide a template for an employee termination checklist.",
            "What are the most common mistakes to avoid when drafting a workplace emergency preparedness plan?",
        ]
    },
    {
        category: "Prompts for Immigration lawyers",
        prompts: [
            "Draft a memorandum of understanding for a family seeking asylum",
            "Draft a visa application for an employment-based immigration",
            "Write a request for evidence response for an H-1B visa applicant",
            "Write a waiver application for a client seeking to overcome a ground of inadmissibility",
            "What should be included in a marriage-based green card application?",
            "What are the standard clauses for an EB-5 investor visa petition?",
            "What are the necessary elements for a successful U visa application?",
            "What are the typical terms for a labor condition application?",
            "What are the recommended provisions for an O-1 visa application?",
            "Provide a template for a naturalization application",
            "What are the most common mistakes to avoid when drafting a K-1 fiancé(e) visa application?",
            "Draft a letter of support for a VAWA self-petitioner",
            "Draft an adjustment of status application for a DACA recipient",
            "Write a hardship waiver application for a client facing deportation",
            "Write an asylum application for a client fleeing persecution",
            "What should be included in an E-2 treaty investor visa application?",
            "What are the standard clauses for an L-1 intra-company transferee visa application?",
            "What are the necessary elements for a successful I-601A provisional waiver application?",
            "What are the typical terms for an I-130 family-based immigrant visa petition?",
            "What are the recommended provisions for a T visa application for victims of human trafficking?",
            "Provide a template for a consular processing application",
            "What are the most common mistakes to avoid when drafting an affidavit of support?",
            "Draft a legal brief for an immigration court hearing",
            "Draft a cancellation of removal application for a non-permanent resident",
            "Write a parole in place application for a military family member",
            "Write a motion to reopen for a client with a removal order",
            "What should be included in an H-2A temporary agricultural worker visa application?",
            "What are the standard clauses for an H-2B temporary non-agricultural worker visa application?",
            "What are the necessary elements for a successful I-212 application for permission to reapply for admission?",
            "What are the typical terms for an I-751 petition to remove conditions on residence?",
            "What are the recommended provisions for a J-1 waiver application?",
            "Provide a template for an I-539 application to extend or change non-immigrant status",
            "What are the most common mistakes to avoid when drafting a G-28 notice of entry of appearance as an attorney or accredited representative?",
            "Draft a legal memorandum analyzing the impact of a new immigration law or policy",
            "Draft a response to a notice of intent to deny for an immigration benefit",
            "Write a cover letter for an employment authorization document application",
            "Write a request for continuance in an immigration court proceeding",
            "What should be included in a TN NAFTA professionals visa application?",
            "What are the standard clauses for an R-1 religious worker visa application?",
            "What are the necessary elements for a successful I-824 application for action on an approved application or petition?",
            "What are the typical terms for an I-765 application for employment authorization?",
            "What are the recommended provisions for an I-360 petition for Amerasian, Widow(er), or Special Immigrant?",
            "Provide a template for a B-1/B-2 visitor visa application",
            "What are the most common mistakes to avoid when drafting an I-131 application for a travel document?",
        ]
    },
    {
        category: "Prompts for Business lawyers",
        prompts: [
            "Draft a Non-Disclosure Agreement for a startup seeking investment.",
            "Draft a Shareholder Agreement for a family-owned business.",
            "Write a Cease and Desist Letter for a trademark infringement case.",
            "Write a Sales Agreement for a business selling products to a distributor.",
            "What should be included in a Lease Agreement for a commercial property?",
            "What are the standard clauses for a Partnership Agreement?",
            "What are the necessary elements for a Licensing Agreement?",
            "What are the typical terms for a Franchise Agreement?",
            "What are the recommended provisions for an Employment Contract?",
            "Provide a template for a Promissory Note.",
            "What are the most common mistakes to avoid when drafting a Power of Attorney?",
            "Write a telecommuting policy for a remote work environment.",
            "Draft a Service Agreement for a freelance web developer.",
            "Draft a Joint Venture Agreement for two companies collaborating on a project.",
            "Write an Intellectual Property Assignment Agreement for a software company.",
            "Write a Privacy Policy for an e-commerce website.",
            "What should be included in a Terms of Use Agreement for an online platform?",
            "What are the standard clauses for a Loan Agreement?",
            "What are the necessary elements for a Sponsorship Agreement?",
            "What are the typical terms for a Settlement Agreement?",
            "What are the recommended provisions for a Contractor Agreement?",
            "Provide a template for a Buy-Sell Agreement.",
            "What are the most common mistakes to avoid when drafting a Confidentiality Agreement?",
            "Draft a Release of Liability Waiver for a sports event.",
            "Draft a Software Development Agreement for a mobile app.",
            "Write a Property Management Agreement for a rental property.",
            "Write a Merger Agreement for two competing companies.",
            "What should be included in a Consulting Agreement for a business consultant?",
            "What are the standard clauses for an Independent Contractor Agreement?",
            "What are the necessary elements for a Prenuptial Agreement?",
            "What are the typical terms for a Severance Agreement?",
            "What are the recommended provisions for a Distribution Agreement?",
            "Provide a template for a Letter of Intent for a business acquisition.",
            "What are the most common mistakes to avoid when drafting a Non-Compete Agreement?",
            "Draft an Asset Purchase Agreement for a business acquisition.",
            "Draft a Stock Purchase Agreement for a company buyout.",
            "Write a Warranty Agreement for a product manufacturer.",
            "Write a Commercial Lease Termination Agreement for a tenant vacating a property.",
            "What should be included in a Real Estate Purchase Agreement?",
            "What are the standard clauses for a Mortgage Agreement?",
            "What are the necessary elements for a Security Agreement?",
            "What are the typical terms for an Operating Agreement for an LLC?",
            "What are the recommended provisions for a Supply Agreement?",
            "Provide a template for a Licensing Agreement for a patented invention.",
            "What are the most common mistakes to avoid when drafting a Subscription Agreement?",
            "Draft a Co-Founder Agreement for a technology startup.",
            "Draft a Manufacturing Agreement for a product company.",
            "Write a Reseller Agreement for a software company.",
            "Write a Collaboration Agreement for two artists working on a project.",
            "What should be included in a Custody Agreement for divorcing parents?",
            "What are the standard clauses for a Trust Agreement?",
            "What are the necessary elements for a Will and Testament?",
            "What are the typical terms for an Escrow Agreement?",
            "What are the recommended provisions for a Master Services Agreement?",
            "Provide a template for a Freelance Writer Agreement.",
            "What are the most common mistakes to avoid when drafting a Website Development Agreement?",
            "Draft an Indemnity Agreement for a construction project.",
            "Draft a Memorandum of Understanding for a nonprofit organization.",
            "Write a Retainer Agreement for a law firm.",
            "Write a Construction Contract for a residential property.",
            "What should be included in a Royalty Agreement for a book author?",
            "What are the standard clauses for a Change of Control Agreement?",
            "What are the necessary elements for a Debt Settlement Agreement?",
            "What are the typical terms for a Pledge Agreement?",
            "What are the recommended provisions for an Advertising Agreement?",
            "Provide a template for a Domain Name Purchase Agreement.",
            "What are the most common mistakes to avoid when drafting a Commercial Sublease Agreement?",
        ]
    },
    {
        category: "Prompts for Tax lawyers",
        prompts: [
            "Draft a memorandum of understanding for a joint venture between two companies",
            "Draft a non-disclosure agreement for a software development company and a freelance developer",
            "Write a partnership agreement for a new law firm",
            "Write a will and testament for client John Doe",
            "What should be included in a commercial lease agreement?",
            "What are the standard clauses for a power of attorney document?",
            "What are the necessary elements for a prenuptial agreement?",
            "What are the typical terms for an employment contract?",
            "What are the recommended provisions for a shareholder agreement?",
            "Provide a template for a promissory note",
            "What are the most common mistakes to avoid when drafting a service level agreement?",
            "Draft a property purchase agreement for a residential property transaction",
            "Draft a software license agreement for a SaaS company and its customers",
            "Write a living trust for client Jane Smith",
            "Write a cease and desist letter for a trademark infringement issue",
            "What should be included in a general release of liability?",
            "What are the standard clauses for a consulting agreement?",
            "What are the necessary elements for a warranty deed?",
            "What are the typical terms for a franchise agreement?",
            "What are the recommended provisions for a construction contract?",
            "Provide a template for a loan agreement",
            "What are the most common mistakes to avoid when drafting a non-compete agreement?",
            "Draft a separation agreement for a divorcing couple",
            "Draft a licensing agreement for a patent holder and a manufacturer",
            "Write bylaws document for a non-profit organization",
            "Write a letter of intent for a business acquisition",
            "What should be included in a bill of sale for a vehicle?",
            "What are the standard clauses for an independent contractor agreement?",
            "What are the necessary elements for a quitclaim deed?",
            "What are the typical terms for a sublease agreement?",
            "Draft a Co-Founder Agreement for a technology startup.",
            "Draft a Manufacturing Agreement for a product company.",
            "Write a Reseller Agreement for a software company.",
            "Write a Collaboration Agreement for two artists working on a project.",
            "What should be included in a Custody Agreement for divorcing parents?",
            "What are the standard clauses for a Trust Agreement?",
            "What are the necessary elements for a Will and Testament?",
            "What are the typical terms for an Escrow Agreement?",
            "What are the recommended provisions for a Master Services Agreement?",
            "Provide a template for a Freelance Writer Agreement.",
            "What are the most common mistakes to avoid when drafting a Website Development Agreement?",
            "Draft an Indemnity Agreement for a construction project.",
            "Draft a Memorandum of Understanding for a nonprofit organization.",
            "Write a Retainer Agreement for a law firm.",
            "Write a Construction Contract for a residential property.",
            "What should be included in a Royalty Agreement for a book author?",
            "What are the standard clauses for a Change of Control Agreement?",
            "What are the necessary elements for a Debt Settlement Agreement?",
            "What are the typical terms for a Pledge Agreement?",
            "What are the recommended provisions for an Advertising Agreement?",
            "Provide a template for a Domain Name Purchase Agreement.",
            "What are the most common mistakes to avoid when drafting a Commercial Sublease Agreement?",
            "What are the recommended provisions for a settlement agreement?",
            "Provide a template for a confidentiality agreement",
            "What are the most common mistakes to avoid when drafting a merger agreement?",
            "Draft a stock purchase agreement for a business owner selling shares to an investor",
            "Draft a sponsorship agreement for a sports team and a corporate sponsor",
            "Write a terms of service document for an e-commerce website",
            "Write a privacy policy for a mobile app",
            "What should be included in a letter of demand for unpaid invoices?",
            "What are the standard clauses for a distribution agreement?",
            "What are the necessary elements for a personal guarantee?",
            "What are the typical terms for a management agreement?",
            "What are the recommended provisions for an intellectual property assignment agreement?",
            "Provide a template for a sales agreement",
            "What are the most common mistakes to avoid when drafting a buy-sell agreement?",
            "Draft an option agreement for the purchase of real estate",
            "Draft a master services agreement for a marketing agency and a client",
            "Write a retainer agreement for a law firm and a client",
            "Write a deed of trust for a real estate transaction",
            "What should be included in an affidavit of support?",
            "What are the standard clauses for a manufacturing agreement?",
            "What are the necessary elements for a hold harmless agreement?",
            "What are the typical terms for a software development agreement?",
            "What are the recommended provisions for a joint venture agreement?",
            "Provide a template for an operating agreement for a limited liability company (LLC)",
            "What are the most common mistakes to avoid when drafting a professional services agreement?",
            "Draft a guardianship agreement for a minor child",
            "Draft a mediation agreement for a dispute resolution",
            "Write a collective bargaining agreement for an employer and a labor union",
            "Write a donation agreement for a charitable organization",
            "What should be included in an indemnification agreement?",
            "What are the standard clauses for a work-for-hire agreement?",
            "What are the necessary elements for a real estate purchase contract?",
            "What are the typical terms for a convertible note agreement?",
            "What are the recommended provisions for a royalty agreement?",
            "Provide a template for a debt settlement agreement",
            "What are the most common mistakes to avoid when drafting an asset purchase agreement?",
        ]
    },
    {
        category: "Prompts for Real Estate lawyers",
        prompts: [
            "Draft a Residential Lease Agreement for a landlord and tenant",
            "Draft a Purchase Agreement for a buyer and seller",
            "Write an Easement Agreement for a property owner and neighbor",
            "Write a Commercial Lease Agreement for ABC Corporation",
            "What should be included in a Deed of Trust?",
            "What are the standard clauses for a Land Installment Contract?",
            "What are the necessary elements for a Mortgage Agreement?",
            "What are the typical terms for a Property Management Agreement?",
            "What are the recommended provisions for a Real Estate Option Agreement?",
            "Provide a template for a Joint Venture Agreement in a real estate development project",
            "What are the most common mistakes to avoid when drafting a Quitclaim Deed?",
            "Draft a Notice to Vacate for a landlord and tenant",
            "Draft a Real Estate Partnership Agreement for two investors",
            "Write a Rent-to-Own Agreement for a property owner and prospective buyer",
            "Write a Letter of Intent to purchase commercial property for XYZ Company",
            "What should be included in a Right of First Refusal Agreement?",
            "What are the standard clauses for a Construction Contract?",
            "What are the necessary elements for a Landlord's Lien Waiver?",
            "What are the typical terms for a Tenant Estoppel Certificate?",
            "What are the recommended provisions for a Sublease Agreement?",
            "Provide a template for a Real Estate Development Agreement",
            "What are the most common mistakes to avoid when drafting a Promissory Note secured by real property?",
            "Draft a Homeowners Association Bylaws for a residential community",
            "Draft a Declaration of Covenants, Conditions, and Restrictions for a real estate developer",
            "Write a Zoning Variance Request for a property owner",
            "Write a Title Opinion for a real estate attorney",
            "What should be included in a Ground Lease Agreement?",
            "What are the standard clauses for a Real Estate Commission Agreement?",
            "What are the necessary elements for a Real Estate Non-Disclosure Agreement?",
            "What are the typical terms for a Real Estate Confidentiality Agreement?",
            "What are the recommended provisions for a Real Estate Indemnity Agreement?",
            "Provide a template for a Real Estate Co-Brokerage Agreement",
            "What are the most common mistakes to avoid when drafting a Real Estate Assignment Agreement?",
            "Draft a Warranty Deed for a seller and buyer of residential property",
            "Draft a Land Contract for a property owner and buyer",
            "Write a Boundary Line Agreement for two adjoining property owners",
            "Write a Notice of Lis Pendens for a real estate attorney",
            "What should be included in a Lease Termination Agreement?",
            "What are the standard clauses for a Lease Extension Agreement?",
            "What are the necessary elements for a Lease Amendment?",
            "What are the typical terms for a Lease Guaranty?",
            "What are the recommended provisions for a Lease Subordination Agreement?",
            "Provide a template for a Lease Assignment Agreement",
            "What are the most common mistakes to avoid when drafting a Lease Option Agreement?",
            "Draft a Letter of Intent to Lease for a commercial tenant",
            "Draft a Broker's Opinion of Value for a real estate broker",
            "Write a Letter of Intent to Sell for a property owner",
            "Write a Real Estate Closing Statement for a real estate attorney",
            "What should be included in an Escrow Agreement?",
            "What are the standard clauses for a Real Estate Sales Contract?",
            "What are the necessary elements for a Real Estate Tax Indemnity Agreement?",
            "What are the typical terms for a Real Estate Co-Ownership Agreement?",
            "What are the recommended provisions for a Real Estate Power of Attorney?",
            "Provide a template for a Real Estate Offer and Acceptance Agreement",
            "What are the most common mistakes to avoid when drafting a Real Estate Purchase and Sale Agreement?",
            "Draft a Letter of Intent to Purchase for a prospective buyer",
            "Draft a Real Estate Contingency Agreement for a buyer and seller",
            "Write a Real Estate Disclosure Statement for a property seller",
            "Write a Real Estate Hold Harmless Agreement for a real estate agent",
            "What should be included in a Real Estate Finders Fee Agreement?",
            "What are the standard clauses for a Real Estate Investment Agreement?",
            "What are the necessary elements for a Real Estate Syndication Agreement?",
            "What are the typical terms for a Real Estate Referral Agreement?",
            "What are the recommended provisions for a Real Estate Commission Dispute Resolution Agreement?",
            "Provide a template for a Real Estate Brokerage Representation Agreement",
            "What are the most common mistakes to avoid when drafting a Real Estate Marketing Agreement?",
        ]
    },
    {
        category: "Prompts for Intellectual Property (IP) lawyers",
        prompts: [
            "Draft a patent application for a new invention",
            "Draft a trademark registration application for a company logo",
            "Write a copyright infringement cease and desist letter for a client's protected work",
            "Write a software licensing agreement for John's Tech Company",
            "What should be included in a non-disclosure agreement?",
            "What are the standard clauses for a trade secret license agreement?",
            "What are the necessary elements for a work-for-hire agreement?",
            "What are the typical terms for an intellectual property assignment agreement?",
            "What are the recommended provisions for a joint development agreement?",
            "Provide a template for a patent license agreement",
            "What are the most common mistakes to avoid when drafting a trademark coexistence agreement?",
            "Draft a design patent application for a unique product design",
            "Draft a domain name purchase agreement for an online business",
            "Write an infringement response letter for a patent holder",
            "Write a copyright takedown notice for Jane Doe's photography website",
            "What should be included in a music licensing agreement?",
            "What are the standard clauses for a royalty agreement?",
            "What are the necessary elements for a trademark license agreement?",
            "What are the typical terms for a technology transfer agreement?",
            "What are the recommended provisions for a software development agreement?",
            "Provide a template for a merchandising agreement",
            "What are the most common mistakes to avoid when drafting an intellectual property indemnification clause?",
            "Draft a plant variety protection application for a new crop variety",
            "Draft a moral rights waiver agreement for an artist's commissioned work",
            "Write a patent invalidity opinion letter for a client facing infringement allegations",
            "Write a trademark opposition filing for a client's competing brand",
            "What should be included in a book publishing agreement?",
            "What are the standard clauses for a content licensing agreement?",
            "What are the necessary elements for a patent co-ownership agreement?",
            "What are the typical terms for a software escrow agreement?",
            "What are the recommended provisions for a data sharing agreement?",
            "Provide a template for a copyright transfer agreement",
            "What are the most common mistakes to avoid when drafting an invention disclosure form?",
            "Draft a utility model application for a technical innovation",
            "Draft a research collaboration agreement for a university and a private company",
            "Write a freedom to operate opinion letter for a product manufacturer",
            "Write a copyright fair use analysis for a documentary filmmaker",
            "What should be included in a film production agreement?",
            "What are the standard clauses for a patent litigation settlement?",
            "What are the necessary elements for a trademark maintenance and renewal agreement?",
            "What are the typical terms for a multimedia licensing agreement?",
            "What are the recommended provisions for an open-source software license?",
            "Provide a template for an intellectual property due diligence report",
            "What are the most common mistakes to avoid when drafting a confidentiality clause in an IP agreement?",
            "Draft a geographic indication registration application for a regional product",
            "Draft an inter partes review petition for a patent challenge",
            "Write an intellectual property valuation report for a company acquisition",
            "Write a trademark cancellation petition for a client's abandoned mark",
            "What should be included in a patent pooling agreement?",
            "What are the standard clauses for a cross-licensing agreement?",
            "What are the necessary elements for a software maintenance and support agreement?",
            "What are the typical terms for an IP pledge agreement?",
            "What are the recommended provisions for a database rights agreement?",
            "Provide a template for a cease and desist response letter in an IP dispute",
            "What are the most common mistakes to avoid when drafting an intellectual property audit plan?",
        ]
    },
    {
        category: "Prompts for Criminal Defense lawyers",
        prompts: [
            "Draft a motion to suppress evidence for an illegal search and seizure case",
            "Draft an affidavit in support of a client's self-defense claim",
            "Write a memorandum of law for a criminal defense motion",
            "Write a plea agreement for a client charged with a non-violent crime",
            "What should be included in a pretrial discovery request?",
            "What are the standard clauses for a criminal defense retainer agreement?",
            "What are the necessary elements for a motion to dismiss based on a violation of the right to a speedy trial?",
            "What are the typical terms for a plea bargain in a drug possession case?",
            "What are the recommended provisions for a criminal defense attorney's closing argument?",
            "Provide a template for a criminal defense opening statement",
            "What are the most common mistakes to avoid when drafting a motion for a new trial?",
            "Draft a motion in limine to exclude prejudicial evidence in a criminal trial",
            "Draft a sentencing memorandum for a client convicted of a white-collar crime",
            "Write a post-conviction relief petition for a client claiming ineffective assistance of counsel",
            "Write a letter to the prosecutor requesting a reduction of charges for a first-time offender",
            "What should be included in a client's declaration in support of a motion for bail reduction?",
            "What are the standard clauses for a criminal defense witness subpoena?",
            "What are the necessary elements for a writ of habeas corpus?",
            "What are the typical terms for an expungement request?",
            "What are the recommended provisions for a jury instruction on reasonable doubt?",
            "Provide a template for a notice of appeal in a criminal case",
            "What are the most common mistakes to avoid when drafting a motion to set aside a guilty plea?",
            "Draft a motion for judgment of acquittal following a guilty verdict",
            "Draft a letter to the client outlining potential defenses and case strategy",
            "Write a motion for a change of venue due to pretrial publicity",
            "Write a request for a bill of particulars to clarify the charges against a client",
            "What should be included in a motion for recusal of a judge for bias?",
            "What are the standard clauses for a criminal defense attorney's fee agreement?",
            "What are the necessary elements for a motion to strike a prior conviction?",
            "What are the typical terms for a diversion program agreement?",
            "What are the recommended provisions for a jury instruction on the presumption of innocence?",
            "Provide a template for a petition for clemency or pardon",
            "What are the most common mistakes to avoid when drafting a motion for the appointment of an expert witness?",
            "Draft a motion to sever charges for a client facing multiple counts",
            "Draft a request for production of exculpatory evidence under the Brady rule",
            "Write a motion to quash an improperly issued arrest warrant",
            "Write an opposition to the prosecution's motion to admit certain evidence at trial",
            "What should be included in a motion to disqualify a juror for bias?",
            "What are the standard clauses for a criminal defense attorney's engagement letter?",
            "What are the necessary elements for a motion to suppress a coerced confession?",
            "What are the typical terms for a deferred prosecution agreement?",
            "What are the recommended provisions for a jury instruction on the burden of proof?",
            "Provide a template for a notice of alibi defense",
            "What are the most common mistakes to avoid when drafting a motion to enforce a plea agreement?",
            "Draft a motion for a mistrial based on juror misconduct",
            "Draft a response to a prosecution's motion for a pretrial hearing",
            "Write a motion to compel discovery from the prosecution",
            "Write a petition for post-conviction DNA testing",
            "What should be included in a motion to challenge the legality of a search warrant?",
            "What are the standard clauses for a criminal defense attorney's conflict of interest waiver?",
            "What are the necessary elements for a motion to dismiss for prosecutorial misconduct?",
            "What are the typical terms for a house arrest or electronic monitoring agreement?",
            "What are the recommended provisions for a jury instruction on eyewitness testimony?",
            "Provide a template for a notice of intent to introduce expert testimony",
            "What are the most common mistakes to avoid when drafting a motion to challenge the admissibility of a prior conviction?",
        ]
    }
]

export default prebuildPrompts;